services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    user: root
    privileged: true
    container_name: portfolio-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite3:///app/sqlite3_data/portfolio_db
      - PORT=5000
    volumes:
      - ./sqlite3_data:/app/sqlite3_data
    networks:
      - portfolio-network

  # Frontend React App
  portfolio-react:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    privileged: true
    ports:
      - "3000:80"
    container_name: portfolio-react-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
